imports:
  - { resource: 'monolog.yaml' }
  - { resource: '../src/TaskUploader/Config/config.yaml' }

parameters:
    application:
        name: 'WBS AI Extractor'
    
    # Kernel parameters
    kernel.logs_dir: '%kernel.project_dir%/var/log'
    kernel.debug: true
    kernel.environment: 'dev'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Manual definition of PSR/Guzzle services
    Psr\Http\Client\ClientInterface: '@GuzzleHttp\Client'
    Psr\Http\Message\RequestFactoryInterface: '@GuzzleHttp\Psr7\HttpFactory'
    Psr\Http\Message\StreamFactoryInterface: '@GuzzleHttp\Psr7\HttpFactory'

    GuzzleHttp\Client: ~
    GuzzleHttp\Psr7\HttpFactory: ~

  # Aliases
    Psr\Log\LoggerInterface: '@monolog.logger'