parameters:
    redmine.url: 'http://redmine:3000'
    redmine.api_key: 'f90887cb84194e3696d5f5c5ac2837c68907800f'

    # Default Redmine configuration for tasks
    redmine.default.tracker: 'Požadavek'
    redmine.default.status: 'Nový'
    redmine.default.priority: 'Default'

    # WBS configuration
    wbs.spreadsheet_name: 'WBS - vývoj'
    wbs.column_identifiers:
        taskName: 'A'
        initiative: 'B'
        epic: 'C'
        redmineId: 'D'

    # available field names are parameters of redmine issue:
    # - subject
    # - description
    # - is_private - Use true or false to indicate whether the issue is private or not
    # - estimated_hours - Number of hours estimated for issue

    # custom_field is a place for name identifier of a redmine custom field
    wbs.column_definition:
        A:
          type: string
          nullable: false
          field: subject

        B:
          type: string

        C:
          type: string

        D:
          type: int

        F:
          type: float
          custom_field: 'Odhad pro programátora'

        K:
          type: float
          calculated: true
          field: estimatedHours

        L:
          type: string
          field: description

        M:
          type: string
          field: acceptanceCriteria

        N:
          type: string
          custom_field: 'Odkaz na specifikaci'