parameters:
    redmine.url: 'http://redmine:3000'
    redmine.api_key: 'f90887cb84194e3696d5f5c5ac2837c68907800f'

    # Default Redmine configuration for tasks
    redmine.default.tracker: 'PoÅ¾adavek'
    redmine.default.status: 'NovÃ½'
    redmine.default.priority: 'Default'
