parameters:
    redmine.url: 'http://localhost:3000' # Example: Your Redmine instance URL
    redmine.api_key: 'YOUR_REDMINE_API_KEY' # Example: Your Redmine API key

    # Default Redmine configuration for tasks
    redmine.default.tracker: 'Požadavek'
    redmine.default.status: 'Nový'
    redmine.default.priority: 'Default'

    # WBS configuration
    wbs.spreadsheet_name: 'WBS - vývoj'
    wbs.column_identifiers:
        taskName: 'A'
        initiative: 'B'
        epic: 'C'
        redmineId: 'D'

    # custom_field is a place for name identifier of a redmine custom field
    wbs.column_definition:
        A:
          type: string
          nullable: false
          field: subject

        B:
          type: string

        C:
          type: string

        D:
          type: int

        F:
          type: float
          custom_field: 'Odhad pro programátora'

        K:
          type: float
          calculated: true
          field: estimatedHours

        L:
          type: string
          field: description

        M:
          type: string
          field: acceptanceCriteria

        N:
          type: string
          custom_field: 'Odkaz na specifikaci'