parameters:
    redmine.url: 'http://localhost:3000' # Example: Your Redmine instance URL
    redmine.api_key: 'YOUR_REDMINE_API_KEY' # Example: Your Redmine API key

    # Default Redmine configuration for tasks
    redmine.default.tracker: 'Požadavek'
    redmine.default.status: 'Nový'
    redmine.default.priority: 'Default'

    # WBS configuration
    wbs.worksheet_definitions:
        -
            name: 'WBS - vývoj'
            
            column_identifiers:
                taskName: 'A'
                initiative: 'B'
                epic: 'C'
                redmineId: 'D'
                estimatedHours: 'K'
            
            column_definition:
                A:
                    type: string
                    nullable: false
                    field: subject
                B:
                    type: string
                C:
                    type: string
                D:
                    type: int
                F:
                    type: float
                    custom_field: 'Odhad pro programátora'
                K:
                    type: float
                    calculated: true
                    field: estimatedHours
                L:
                    type: string
                    field: description
                M:
                    type: string
                    field: acceptanceCriteria
                N:
                    type: string
                    custom_field: 'Odkaz na specifikaci'
        -
            name: 'WBS - operativní činnosti'
            
            column_identifiers:
                taskName: 'A'
                initiative: 'B'
                epic: 'C'
                redmineId: 'D'
                estimatedHours: 'E'
            
            column_definition:
                A:
                    type: string
                    nullable: false
                    field: subject
                B:
                    type: string
                C:
                    type: string
                D:
                    type: int
                E:
                    type: float
                    calculated: true
                    field: estimatedHours
                F:
                    type: string
                    field: description